
rm(list = ls())
set.seed(123)
library(dplyr); library(tidyr) ;library(Seurat);library(qs2);library(Seurat);library(ggplot2)
library(cowplot);library(presto)
sce.all <- qs_read("sce.all_int_2.1singlet.qs2")  

cluster0_markers <- FindMarkers(sce.all, ident.1 = 0, min.pct = 0.25, logfc.threshold = 0.25)
write.csv(cluster0_markers, file = "cluster0_markers.csv", row.names = TRUE)
cluster1_markers <- FindMarkers(sce.all, ident.1 = 1, min.pct = 0.25, logfc.threshold = 0.25)
write.csv(cluster1_markers, file = "cluster1_markers.csv", row.names = TRUE)
cluster2_markers <- FindMarkers(sce.all, ident.1 = 2, min.pct = 0.25, logfc.threshold = 0.25)
write.csv(cluster2_markers, file = "cluster2_markers.csv", row.names = TRUE)
cluster3_markers <- FindMarkers(sce.all, ident.1 = 3, min.pct = 0.25, logfc.threshold = 0.25)
write.csv(cluster3_markers, file = "cluster3_markers.csv", row.names = TRUE)
cluster4_markers <- FindMarkers(sce.all, ident.1 = 4, min.pct = 0.25, logfc.threshold = 0.25)
write.csv(cluster4_markers, file = "cluster4_markers.csv", row.names = TRUE)
cluster5_markers <- FindMarkers(sce.all, ident.1 = 5, min.pct = 0.25, logfc.threshold = 0.25)
write.csv(cluster5_markers, file = "cluster5_markers.csv", row.names = TRUE)
cluster6_markers <- FindMarkers(sce.all, ident.1 = 6, min.pct = 0.25, logfc.threshold = 0.25)
write.csv(cluster6_markers, file = "cluster6_markers.csv", row.names = TRUE)
cluster7_markers <- FindMarkers(sce.all, ident.1 = 7, min.pct = 0.25, logfc.threshold = 0.25)
write.csv(cluster7_markers, file = "cluster7_markers.csv", row.names = TRUE)
cluster8_markers <- FindMarkers(sce.all, ident.1 = 8, min.pct = 0.25, logfc.threshold = 0.25)
write.csv(cluster8_markers, file = "cluster8_markers.csv", row.names = TRUE)
cluster9_markers <- FindMarkers(sce.all, ident.1 = 9, min.pct = 0.25, logfc.threshold = 0.25)
write.csv(cluster9_markers, file = "cluster9_markers.csv", row.names = TRUE)
cluster10_markers <- FindMarkers(sce.all, ident.1 = 10, min.pct = 0.25, logfc.threshold = 0.25)
write.csv(cluster10_markers, file = "cluster10_markers.csv", row.names = TRUE)

cluster11_markers <- FindMarkers(sce.all, ident.1 = 11, min.pct = 0.25, logfc.threshold = 0.25)
write.csv(cluster11_markers, file = "cluster11_markers.csv", row.names = TRUE)
cluster12_markers <- FindMarkers(sce.all, ident.1 = 12, min.pct = 0.25, logfc.threshold = 0.25)
write.csv(cluster12_markers, file = "cluster12_markers.csv", row.names = TRUE)
cluster13_markers <- FindMarkers(sce.all, ident.1 = 13, min.pct = 0.25, logfc.threshold = 0.25)
write.csv(cluster13_markers, file = "cluster13_markers.csv", row.names = TRUE)
cluster14_markers <- FindMarkers(sce.all, ident.1 = 14, min.pct = 0.25, logfc.threshold = 0.25)
write.csv(cluster14_markers, file = "cluster14_markers.csv", row.names = TRUE)
cluster15_markers <- FindMarkers(sce.all, ident.1 = 15, min.pct = 0.25, logfc.threshold = 0.25)
write.csv(cluster15_markers, file = "cluster15_markers.csv", row.names = TRUE)
cluster16_markers <- FindMarkers(sce.all, ident.1 = 16, min.pct = 0.25, logfc.threshold = 0.25)
write.csv(cluster16_markers, file = "cluster16_markers.csv", row.names = TRUE)
cluster17_markers <- FindMarkers(sce.all, ident.1 = 17, min.pct = 0.25, logfc.threshold = 0.25)
write.csv(cluster17_markers, file = "cluster17_markers.csv", row.names = TRUE)
cluster18_markers <- FindMarkers(sce.all, ident.1 = 18, min.pct = 0.25, logfc.threshold = 0.25)
write.csv(cluster18_markers, file = "cluster18_markers.csv", row.names = TRUE)
cluster19_markers <- FindMarkers(sce.all, ident.1 = 19, min.pct = 0.25, logfc.threshold = 0.25)
write.csv(cluster19_markers, file = "cluster19_markers.csv", row.names = TRUE)
cluster20_markers <- FindMarkers(sce.all, ident.1 = 20, min.pct = 0.25, logfc.threshold = 0.25)
write.csv(cluster20_markers, file = "cluster20_markers.csv", row.names = TRUE)

cluster21_markers <- FindMarkers(sce.all, ident.1 = 21, min.pct = 0.25, logfc.threshold = 0.25)
write.csv(cluster21_markers, file = "cluster21_markers.csv", row.names = TRUE)
cluster22_markers <- FindMarkers(sce.all, ident.1 = 22, min.pct = 0.25, logfc.threshold = 0.25)
write.csv(cluster22_markers, file = "cluster22_markers.csv", row.names = TRUE)
cluster23_markers <- FindMarkers(sce.all, ident.1 = 23, min.pct = 0.25, logfc.threshold = 0.25)
write.csv(cluster23_markers, file = "cluster23_markers.csv", row.names = TRUE)
cluster24_markers <- FindMarkers(sce.all, ident.1 = 24, min.pct = 0.25, logfc.threshold = 0.25)
write.csv(cluster24_markers, file = "cluster24_markers.csv", row.names = TRUE)
cluster25_markers <- FindMarkers(sce.all, ident.1 = 25, min.pct = 0.25, logfc.threshold = 0.25)
write.csv(cluster25_markers, file = "cluster25_markers.csv", row.names = TRUE)
cluster26_markers <- FindMarkers(sce.all, ident.1 = 26, min.pct = 0.25, logfc.threshold = 0.25)
write.csv(cluster26_markers, file = "cluster26_markers.csv", row.names = TRUE)
cluster27_markers <- FindMarkers(sce.all, ident.1 = 27, min.pct = 0.25, logfc.threshold = 0.25)
write.csv(cluster27_markers, file = "cluster27_markers.csv", row.names = TRUE)
cluster28_markers <- FindMarkers(sce.all, ident.1 = 28, min.pct = 0.25, logfc.threshold = 0.25)
write.csv(cluster28_markers, file = "cluster28_markers.csv", row.names = TRUE)
cluster29_markers <- FindMarkers(sce.all, ident.1 = 29, min.pct = 0.25, logfc.threshold = 0.25)
write.csv(cluster29_markers, file = "cluster29_markers.csv", row.names = TRUE)
cluster30_markers <- FindMarkers(sce.all, ident.1 = 30, min.pct = 0.25, logfc.threshold = 0.25)
write.csv(cluster30_markers, file = "cluster30_markers.csv", row.names = TRUE)

cluster31_markers <- FindMarkers(sce.all, ident.1 = 31, min.pct = 0.25, logfc.threshold = 0.25)
write.csv(cluster31_markers, file = "cluster31_markers.csv", row.names = TRUE)
cluster32_markers <- FindMarkers(sce.all, ident.1 = 32, min.pct = 0.25, logfc.threshold = 0.25)
write.csv(cluster32_markers, file = "cluster32_markers.csv", row.names = TRUE)
cluster33_markers <- FindMarkers(sce.all, ident.1 = 33, min.pct = 0.25, logfc.threshold = 0.25)
write.csv(cluster33_markers, file = "cluster33_markers.csv", row.names = TRUE)
cluster34_markers <- FindMarkers(sce.all, ident.1 = 34, min.pct = 0.25, logfc.threshold = 0.25)
write.csv(cluster34_markers, file = "cluster34_markers.csv", row.names = TRUE)
cluster35_markers <- FindMarkers(sce.all, ident.1 = 35, min.pct = 0.25, logfc.threshold = 0.25)
write.csv(cluster35_markers, file = "cluster35_markers.csv", row.names = TRUE)
cluster36_markers <- FindMarkers(sce.all, ident.1 = 36, min.pct = 0.25, logfc.threshold = 0.25)
write.csv(cluster36_markers, file = "cluster36_markers.csv", row.names = TRUE)
cluster37_markers <- FindMarkers(sce.all, ident.1 = 37, min.pct = 0.25, logfc.threshold = 0.25)
write.csv(cluster37_markers, file = "cluster37_markers.csv", row.names = TRUE)
cluster38_markers <- FindMarkers(sce.all, ident.1 = 38, min.pct = 0.25, logfc.threshold = 0.25)
write.csv(cluster38_markers, file = "cluster38_markers.csv", row.names = TRUE)
cluster39_markers <- FindMarkers(sce.all, ident.1 = 39, min.pct = 0.25, logfc.threshold = 0.25)
write.csv(cluster39_markers, file = "cluster39_markers.csv", row.names = TRUE)
cluster40_markers <- FindMarkers(sce.all, ident.1 = 40, min.pct = 0.25, logfc.threshold = 0.25)
write.csv(cluster40_markers, file = "cluster40_markers.csv", row.names = TRUE)

cluster41_markers <- FindMarkers(sce.all, ident.1 = 41, min.pct = 0.25, logfc.threshold = 0.25)
write.csv(cluster41_markers, file = "cluster41_markers.csv", row.names = TRUE)
cluster42_markers <- FindMarkers(sce.all, ident.1 = 42, min.pct = 0.25, logfc.threshold = 0.25)
write.csv(cluster42_markers, file = "cluster42_markers.csv", row.names = TRUE)
cluster43_markers <- FindMarkers(sce.all, ident.1 = 43, min.pct = 0.25, logfc.threshold = 0.25)
write.csv(cluster43_markers, file = "cluster43_markers.csv", row.names = TRUE)


